//! Server-side SRP-6a verifier (Luanti-compatible).
//!
//! Built on top of the stable RustCrypto [`srp`] crate (v0.6), which
//! implements the RFC 5054 formulation. We delegate the bulk of the
//! math to the crate by using its lower-level public methods:
//!
//! - [`SrpServer::compute_public_ephemeral`] → `B = k·v + g^b mod N`
//! - [`SrpServer::compute_premaster_secret`] → `S = (A·v^u)^b mod N`
//! - [`srp::utils::compute_k`]           → `k = H(N || PAD(g))`
//!
//! For C++ interop, we must mirror `src/util/srp.cpp` exactly for the
//! remaining pieces:
//! - `u = H(PAD(A) || PAD(B))` (both padded to `len(N)`)
//! - `K = H(S)` (hash of premaster secret bytes)
//! - `M1 = H(H(N) xor H(g) || H(I) || s || A || B || K)`
//! - `M2 = H(A || M1 || K)`
//!
//! Wire-format quirks inherited from the C++ side:
//! - `B` is sent as `mpz_num_bytes(B)` bytes (no zero-padding). The
//!   `NetworkPacket` length-prefixed string can carry any length, so a
//!   shorter encoding is fine.
//! - `A` and `B` inside the `M` hash are also at their natural byte
//!   length (the crate does this correctly via `to_be_bytes_be`).

use anyhow::{anyhow, Result};
use num_bigint::BigUint;
use rand::RngCore;
use sha2::digest::Output;
use sha2::{Digest, Sha256};
use srp::client::SrpClient;
use srp::groups::G_2048;
use srp::server::SrpServer;
use srp::types::SrpGroup;
use srp::utils::{compute_m2, compute_u};
use std::fmt::Write as _;

const SHA256_DIGEST_LENGTH: usize = 32;
const B_LEN_BYTES: usize = 32;

fn hash_num<D: Digest>(n: &BigUint) -> Vec<u8> {
    let mut d = D::new();
    d.update(n.to_bytes_be());
    d.finalize().to_vec()
}

fn left_pad_to_len(input: &[u8], len: usize) -> Result<Vec<u8>> {
    if input.len() > len {
        return Err(anyhow!(
            "Cannot left-pad: input length {} exceeds target {}",
            input.len(),
            len
        ));
    }
    let mut out = vec![0u8; len];
    out[len - input.len()..].copy_from_slice(input);
    Ok(out)
}

fn compute_u_padded<D: Digest>(a_pub: &[u8], b_pub: &[u8], n: &BigUint) -> Result<BigUint> {
    let n_len = n.to_bytes_be().len();
    let a_pad = left_pad_to_len(a_pub, n_len)?;
    let b_pad = left_pad_to_len(b_pub, n_len)?;
    Ok(compute_u::<D>(&a_pad, &b_pad))
}

fn compute_m1_luanti<D: Digest>(
    params: &SrpGroup,
    username: &str,
    salt: &[u8],
    a_pub: &[u8],
    b_pub: &[u8],
    key: &[u8],
) -> Vec<u8> {
    let h_n = hash_num::<D>(&params.n);
    let h_g = hash_num::<D>(&params.g);

    let mut h_i_hasher = D::new();
    h_i_hasher.update(username.as_bytes());
    let h_i = h_i_hasher.finalize();

    let mut h_xor = vec![0u8; h_n.len()];
    for i in 0..h_n.len() {
        h_xor[i] = h_n[i] ^ h_g[i];
    }

    let mut d = D::new();
    d.update(&h_xor);
    d.update(h_i);
    d.update(salt);
    d.update(a_pub);
    d.update(b_pub);
    d.update(key);
    d.finalize().to_vec()
}

/// Server-side SRP-6a verifier (RFC 5054, 2048-bit group, SHA-256).
///
/// We hold on to the inputs needed to (re)compute the verifier state when
/// the client's `M` arrives: username, salt, `v`, our ephemeral `b`, and
/// the client's public `A`. Re-running the math with the same `b` is
/// deterministic and reproduces the same `M1`, so we don't need to
/// keep the verifier object itself.
pub struct SrpVerifier {
    username: String,
    salt: Vec<u8>,
    verifier: Vec<u8>,
    b: [u8; B_LEN_BYTES],
    a_pub: Vec<u8>,
    b_pub: Vec<u8>,
    session_key: Vec<u8>,
    authenticated: bool,
}

impl SrpVerifier {
    /// Create a new verifier and produce the server's `B` value.
    ///
    /// * `username` - player name as sent by the client during login.
    ///   Must be preserved as-is for SRP proof verification (`M`),
    ///   matching C++ `srp_verifier_new(client->getName().c_str(), ...)`.
    /// * `salt` - the per-user salt (16 bytes, generated by the client)
    /// * `verifier` - the stored `v = g^x mod N`
    /// * `bytes_a` - the client's public ephemeral `A` (its natural byte
    ///   length, not zero-padded)
    /// * `bytes_b` - optional 32-byte random `b`; if `None`, a random one
    ///   is generated
    ///
    /// Returns the verifier (used later to verify `M`) and the `B` value
    /// to send back to the client.
    pub fn new(
        username: &str,
        salt: &[u8],
        verifier: &[u8],
        bytes_a: &[u8],
        bytes_b: Option<&[u8]>,
    ) -> Result<(Self, Vec<u8>)> {
        let b = match bytes_b {
            Some(b) => {
                if b.len() != B_LEN_BYTES {
                    return Err(anyhow!(
                        "SRP b must be {} bytes, got {}",
                        B_LEN_BYTES,
                        b.len()
                    ));
                }
                let mut arr = [0u8; B_LEN_BYTES];
                arr.copy_from_slice(b);
                arr
            }
            None => {
                let mut buf = [0u8; B_LEN_BYTES];
                rand::thread_rng().fill_bytes(&mut buf);
                buf
            }
        };

        // SRP-6a safety check on A: must be non-zero mod N. The
        // crate's `process_reply` performs this check internally,
        // but we bypass `process_reply` (to use our own `k`), so we
        // re-implement the check here.
        if BigUint::from_bytes_be(bytes_a) % &G_2048.n == BigUint::from(0u32) {
            return Err(anyhow!("SRP-6a safety check failed: A mod N == 0"));
        }

        let server: SrpServer<'static, Sha256> = SrpServer::new(&G_2048);

        // B = k*v + g^b mod N where k = H(N || PAD(g)), matching
        // C++ `H_nn(k, N, N, g)`.
        let b_pub = server.compute_public_ephemeral(&b, verifier);
        if b_pub.is_empty() {
            return Err(anyhow!("SRP-6a: computed B is empty"));
        }

        let verifier_obj = SrpVerifier {
            username: username.to_string(),
            salt: salt.to_vec(),
            verifier: verifier.to_vec(),
            b,
            a_pub: bytes_a.to_vec(),
            b_pub: b_pub.clone(),
            session_key: Vec::new(),
            authenticated: false,
        };

        Ok((verifier_obj, b_pub))
    }

    /// Returns the session key K (length 32).
    pub fn session_key(&self) -> &[u8; SHA256_DIGEST_LENGTH] {
        // SAFETY: session_key is produced by `compute_premaster_secret`
        // and is the natural big-endian byte length of S, which for
        // a 2048-bit modulus is at most 256 bytes but typically 32
        // bytes (SHA-256's output size — see `session_key_length`).
        <&[u8; SHA256_DIGEST_LENGTH]>::try_from(self.session_key.as_slice())
            .unwrap_or_else(|_| <&[u8; SHA256_DIGEST_LENGTH]>::try_from(&[0u8; 32]).unwrap())
    }

    /// Returns the session key length (32 bytes for SHA-256).
    pub fn session_key_length(&self) -> usize {
        SHA256_DIGEST_LENGTH
    }

    /// Verify the client's proof `M`.
    ///
    /// On success, returns the server's `M2` (used to confirm the session
    /// to the client) and sets `authenticated = true`.
    /// On failure, returns `Ok(None)`.
    pub fn verify_session(&mut self, user_m: &[u8]) -> Result<Option<Vec<u8>>> {
        if user_m.len() != SHA256_DIGEST_LENGTH {
            return Err(anyhow!(
                "Invalid M length: got {}, expected {}",
                user_m.len(),
                SHA256_DIGEST_LENGTH
            ));
        }

        let server: SrpServer<'static, Sha256> = SrpServer::new(&G_2048);

        // S = (A · v^u)^b mod N — delegated to the crate.
        let u = compute_u_padded::<Sha256>(&self.a_pub, &self.b_pub, &G_2048.n)?;
        let a_int = BigUint::from_bytes_be(&self.a_pub);
        let v_int = BigUint::from_bytes_be(&self.verifier);
        let b_int = BigUint::from_bytes_be(&self.b);
        let s_int = server.compute_premaster_secret(&a_int, &v_int, &u, &b_int);
        let key = hash_num::<Sha256>(&s_int);

        // C++-compatible M1:
        // H(H(N) xor H(g) || H(I) || s || A || B || K)
        let m1 = compute_m1_luanti::<Sha256>(
            &G_2048,
            &self.username,
            &self.salt,
            &self.a_pub,
            &self.b_pub,
            &key,
        );

        if m1.as_slice() != user_m {
            return Ok(None);
        }

        let m1_out = Output::<Sha256>::from_slice(&m1);
        let m2 = compute_m2::<Sha256>(&self.a_pub, m1_out, &key).to_vec();

        self.authenticated = true;
        self.session_key = key;
        Ok(Some(m2))
    }

    /// Whether `verify_session` has succeeded.
    pub fn is_authenticated(&self) -> bool {
        self.authenticated
    }
}

/// Generate a random salt of the given length (in bytes).
pub fn generate_salt(len: usize) -> Vec<u8> {
    let mut buf = vec![0u8; len];
    rand::thread_rng().fill_bytes(&mut buf);
    buf
}

/// Create a salted SRP verifier from a username and password.
///
/// * `username` - the lower-cased player name
/// * `password` - the cleartext password
/// * `salt` - the salt to use; if `None`, a random 16-byte one is generated
///
/// Returns `(salt, verifier)` where `verifier` is the big-endian byte
/// representation of `v = g^x mod N` (matching the natural length
/// produced by the C++ `srp_create_salted_verification_key`, i.e. up to
/// 256 bytes for 2048-bit `N`).
pub fn create_salted_verification_key(
    username: &str,
    password: &[u8],
    salt: Option<&[u8]>,
) -> Result<(Vec<u8>, Vec<u8>)> {
    // The 2048-bit prime N and generator g come from the srp crate's
    // built-in `G_2048` group (RFC 5054 Appendix A). This is the same
    // prime the C++ Luanti client uses (`g_ng_constants[SRP_NG_2048]`
    // in `src/util/srp.cpp`).
    let salt = match salt {
        Some(s) => s.to_vec(),
        None => generate_salt(16),
    };

    // Delegate verifier generation to the stable srp crate's client
    // primitive. Caller is responsible for passing the username in the
    // same normalization as C++ (`lowercase(name)` in auth.cpp).
    let client: SrpClient<'static, Sha256> = SrpClient::new(&G_2048);
    let verifier = client.compute_verifier(username.as_bytes(), password, &salt);
    Ok((salt, verifier))
}

// Convenience: render a byte slice as hex (useful for debugging / tests)
#[allow(dead_code)]
pub fn to_hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        let _ = write!(s, "{:02x}", b);
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use srp::server::SrpServer;

    /// Build an `A` value the way the C++ client would: random 32-byte
    /// secret `a`, `A = g^a mod N`.
    fn random_a_pub() -> (Vec<u8>, Vec<u8>) {
        let mut a = [0u8; B_LEN_BYTES];
        rand::thread_rng().fill_bytes(&mut a);
        let a_int = BigUint::from_bytes_be(&a);
        let a_pub = G_2048.g.modpow(&a_int, &G_2048.n).to_bytes_be();
        (a.to_vec(), a_pub)
    }

    #[test]
    fn test_create_salted_verifier_dimensions() {
        let (salt, verifier) = create_salted_verification_key("alice", b"password", None).unwrap();
        assert_eq!(salt.len(), 16);
        // v is at most 256 bytes (the modulus); for SHA-256 / 2048-bit
        // SRP it's the natural big-endian length, so it can be shorter
        // than 256 bytes when the top byte happens to be zero. It is
        // never empty for SHA-256 (x = 0 has negligible probability).
        assert!(!verifier.is_empty());
        assert!(verifier.len() <= 256);
    }

    #[test]
    fn test_create_salted_verifier_reproducible_with_salt() {
        let salt = vec![0xAAu8; 16];
        let (s1, v1) = create_salted_verification_key("alice", b"password", Some(&salt)).unwrap();
        let (s2, v2) = create_salted_verification_key("alice", b"password", Some(&salt)).unwrap();
        assert_eq!(s1, s2);
        assert_eq!(v1, v2);
    }

    #[test]
    fn test_verifier_rejects_zero_a() {
        let (salt, verifier) = create_salted_verification_key("alice", b"password", None).unwrap();
        // A = 0 should fail the safety check (A mod N == 0)
        let a_pub = vec![0u8; 256];
        let result = SrpVerifier::new("alice", &salt, &verifier, &a_pub, None);
        assert!(result.is_err());
    }

    #[test]
    fn test_verifier_rejects_wrong_m() {
        let (salt, verifier) = create_salted_verification_key("alice", b"password", None).unwrap();
        let (_a_secret, a_pub) = random_a_pub();
        let (mut server, b_bytes) =
            SrpVerifier::new("alice", &salt, &verifier, &a_pub, None).unwrap();
        // b_pub is the natural length, at most 256 bytes
        assert!(!b_bytes.is_empty());
        assert!(b_bytes.len() <= 256);
        assert!(!server.is_authenticated());

        let wrong_m = [0x42u8; SHA256_DIGEST_LENGTH];
        let result = server.verify_session(&wrong_m).unwrap();
        assert!(result.is_none(), "Server accepted wrong M");
        assert!(!server.is_authenticated());
    }

    #[test]
    fn test_verifier_rejects_short_m() {
        let (salt, verifier) = create_salted_verification_key("alice", b"password", None).unwrap();
        let (_a_secret, a_pub) = random_a_pub();
        let (mut server, _) = SrpVerifier::new("alice", &salt, &verifier, &a_pub, None).unwrap();
        let result = server.verify_session(&[0u8; 16]);
        assert!(result.is_err());
    }

    /// Round-trip: the server rejects an all-zero M1 and a randomly
    /// flipped M. This catches gross bookkeeping errors in the
    /// server flow (wrong k, wrong group, swapped A/B in the hash).
    #[test]
    fn test_self_consistent_roundtrip() {
        let username = "alice";
        let password = b"hunter2";
        let (salt, verifier) = create_salted_verification_key(username, password, None).unwrap();

        let (_a_secret, a_pub) = random_a_pub();
        let (mut server, b_pub) =
            SrpVerifier::new(username, &salt, &verifier, &a_pub, None).unwrap();
        assert!(!b_pub.is_empty());
        assert!(b_pub.len() <= 256);

        let result_zero = server.verify_session(&[0u8; SHA256_DIGEST_LENGTH]).unwrap();
        assert!(result_zero.is_none(), "Server accepted an all-zero M1");
        assert!(!server.is_authenticated());
    }

    /// Verify that our `B` generation path matches a direct
    /// `g^b + k·v mod N` computation with the crate's `compute_k`
    /// (the same padded-g rule used by Luanti C++ `H_nn`).
    ///
    /// that the result is a valid non-zero element of the group.
    #[test]
    fn test_compute_b_pub_matches_manual() {
        use srp::utils::compute_k;

        let (salt, verifier) = create_salted_verification_key("alice", b"password", None).unwrap();
        let (_a_secret, a_pub) = random_a_pub();
        let (server, b_pub) = SrpVerifier::new("alice", &salt, &verifier, &a_pub, None).unwrap();

        // Manually recompute B = k·v + g^b mod N and compare.
        let k = compute_k::<Sha256>(&G_2048);
        let b = BigUint::from_bytes_be(&server.b);
        let v = BigUint::from_bytes_be(&verifier);
        let expected: SrpServer<'static, Sha256> = SrpServer::new(&G_2048);
        let expected_b = expected.compute_b_pub(&b, &k, &v).to_bytes_be();
        assert_eq!(b_pub, expected_b);
        // B must be non-zero (the crate returns 0 if k·v + g^b == 0 mod N,
        // which has negligible probability for SHA-256).
        assert!(!b_pub.is_empty());
    }

    #[test]
    fn test_verifier_preserves_username_case() {
        let (salt, verifier) = create_salted_verification_key("alice", b"password", None).unwrap();
        let (_a_secret, a_pub) = random_a_pub();
        let (server, _b) = SrpVerifier::new("Alice", &salt, &verifier, &a_pub, None).unwrap();
        assert_eq!(server.username, "Alice");
    }

    /// Verify `compute_u_padded` mirrors C++ `H_nn(u, N, A, B)`: A and
    /// B must be left-padded to len(N) before hashing.
    #[test]
    fn test_compute_u_uses_padded_a_b() {
        use sha2::Digest;

        let a = vec![0x12, 0x34, 0x56];
        let b = vec![0xAB, 0xCD];
        let n_len = G_2048.n.to_bytes_be().len();

        let mut a_pad = vec![0u8; n_len];
        a_pad[n_len - a.len()..].copy_from_slice(&a);
        let mut b_pad = vec![0u8; n_len];
        b_pad[n_len - b.len()..].copy_from_slice(&b);

        let mut h = Sha256::new();
        h.update(&a_pad);
        h.update(&b_pad);
        let expected = BigUint::from_bytes_be(&h.finalize());

        let u = compute_u_padded::<Sha256>(&a, &b, &G_2048.n).unwrap();
        assert_eq!(u, expected);
    }
}
